version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=test123
      - POSTGRES_DB=postgres
